mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('works.urls')),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    # ex: /posts/
    path('', views.index, name='index'),
    # ex: /posts/5/
    path('<int:post_id>/', views.detail, name='detail'),
    # ex: /posts/5/results/
]

works/urls.py
from django.urls import path

from . import views

app_name = 'works'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:work_id>/', views.detail, name='detail'),
]

posts/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    # category = models.ForeignKey(Category, on_delete=models.PROTECT)
    # tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    # description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)
    # pub_date = models.DateTimeField('date published')
    photo = models.ImageField(upload_to='images/', default=False)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_at <= now
    def __str__(self):
        return self.title

works/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Work(models.Model):
    # category = models.ForeignKey(Category, on_delete=models.PROTECT)
    # tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    # description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)
    # pub_date = models.DateTimeField('date published')
    photo = models.ImageField(upload_to='images/', default=False)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_at <= now

    def __str__(self):
        return self.title

posts/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Post

def index(request):
  latest_post_list = Post.objects.order_by('-published_at')[:5]
  context = {'latest_post_list': latest_post_list}
  return render(request, 'posts/index.html', context)


def detail(request, post_id):
  post = get_object_or_404(Post, pk=post_id)
  return render(request, 'posts/detail.html', {'post': post})

works/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Work
from posts.models import Post

def index(request):
    latest_work_list = Work.objects.order_by('-published_at')[:5]
    latest_post_list = Post.objects.order_by('-published_at')[:5]
    context = {'latest_post_list': latest_post_list,'latest_work_list': latest_work_list,}
    return render(request, 'works/index.html', context)

def detail(request, work_id):
    work = get_object_or_404(Work, pk=work_id)
    return render(request, 'works/detail.html', {'work': work})

templates/_partials/head.html
<head>
  <!--Global site tag (gtag.js) - Google Analytics-->
  <script async="async" src="https://www.googletagmanager.com/gtag/js?id=XX-XXXXXXXX-X"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'XX-XXXXXXXX-X');
  </script>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
  <!-- META-->
  <title>Site Title</title>
  <meta name="description" content="ページ説明">
  <meta name="keywords" content="ページキーワード,pagekeyword">
  <meta name="twitter:site" content="http://www.sitetitle.com">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:description" content="ページ説明">
  <meta name="twitter:image:src" content="http://www.sitetitle.com/assets/img/og_image.png">
  <meta property="og:title" content="Site Title">
  <meta property="og:site_name" content="Site Title">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="ja_JP">
  <meta property="og:image" content="http://www.sitetitle.com/assets/img/og_image.png">
  <meta property="og:description" content="ページ説明">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="152x152" href="/assets/favicons/favicon-152x152.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
  <link rel="mask-icon" href="/assets/favicons/safari-pinned-tab.svg" color="#000000">
  <link rel="shortcut icon" href="/assets/favicons/favicon.ico">
  <meta name="msapplication-TileColor" content="#000000">
  <meta name="msapplication-config" content="/assets/favicons/browserconfig.xml">
  <meta name="theme-color" content="#ffffff">{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/app.css' %}">
</head>

templates/includes/footer.html
<!-- footer-->
<footer class="footer"></footer>

templates/includes/header.html
<!-- header-->
<header class="header"></header>

templates/lower/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!--Global site tag (gtag.js) - Google Analytics-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=XX-XXXXXXXX-X"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'XX-XXXXXXXX-X');
    </script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <!-- META-->
    <title> | Site Title</title>
    <meta name="description" content="description">
    <meta name="keywords" content="ページキーワード,pagekeyword,keyword">
    <meta name="twitter:site" content="http://www.sitetitle.com">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:description" content="description">
    <meta name="twitter:image:src" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:title" content=" | Site Title">
    <meta property="og:site_name" content="Site Title">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="ja_JP">
    <meta property="og:image" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:description" content="description">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="152x152" href="/assets/favicons/favicon-152x152.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
    <link rel="mask-icon" href="/assets/favicons/safari-pinned-tab.svg" color="#000000">
    <link rel="shortcut icon" href="/assets/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="msapplication-config" content="/assets/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/app.css' %}">
  </head>
  <body>
    <div class="wrapper">{% include /includes/header %}
      <div>
        <h1>lower</h1>
        <p>下層ページ共通部</p>
        <p>this is lower</p>
        <p>下層ページ共通部</p>
      </div>{% include /includes/footer %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="/assets/js/app.js"></script>
  </body>
</html>

templates/posts/detail.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!--Global site tag (gtag.js) - Google Analytics-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=XX-XXXXXXXX-X"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'XX-XXXXXXXX-X');
    </script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <!-- META-->
    <title>Site Title</title>
    <meta name="description" content="ページ説明">
    <meta name="keywords" content="ページキーワード,pagekeyword">
    <meta name="twitter:site" content="http://www.sitetitle.com">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:description" content="ページ説明">
    <meta name="twitter:image:src" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:title" content="Site Title">
    <meta property="og:site_name" content="Site Title">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="ja_JP">
    <meta property="og:image" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:description" content="ページ説明">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="152x152" href="/assets/favicons/favicon-152x152.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
    <link rel="mask-icon" href="/assets/favicons/safari-pinned-tab.svg" color="#000000">
    <link rel="shortcut icon" href="/assets/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="msapplication-config" content="/assets/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/app.css' %}">
  </head>
  <body>
    <div class="wrapper">{% include /includes/header %}
      <h1>{{ post.title }}</h1>{{ post.content| safe }}<a href="{% url 'posts:index' %}">一覧</a>{% include /includes/footer %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="/assets/js/app.js"></script>
  </body>
</html>

templates/posts/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!--Global site tag (gtag.js) - Google Analytics-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=XX-XXXXXXXX-X"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'XX-XXXXXXXX-X');
    </script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <!-- META-->
    <title>Site Title</title>
    <meta name="description" content="ページ説明">
    <meta name="keywords" content="ページキーワード,pagekeyword">
    <meta name="twitter:site" content="http://www.sitetitle.com">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:description" content="ページ説明">
    <meta name="twitter:image:src" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:title" content="Site Title">
    <meta property="og:site_name" content="Site Title">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="ja_JP">
    <meta property="og:image" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:description" content="ページ説明">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="152x152" href="/assets/favicons/favicon-152x152.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
    <link rel="mask-icon" href="/assets/favicons/safari-pinned-tab.svg" color="#000000">
    <link rel="shortcut icon" href="/assets/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="msapplication-config" content="/assets/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/app.css' %}">
  </head>
  <body>
    <div class="wrapper">{% include /includes/header %}
      <h1>スクロールするとコンテンツがフェードインします</h1>{% if latest_post_list %}
      <link rel="stylesheet" type="text/css" href="{% static 'assets/css/app.css' %}">
      <ul>{% for post in latest_post_list %}
        <li><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></li>    {% endfor %}
      </ul>{% else %}
      <p>No posts are available.</p>{% endif %}<a href="{% url 'posts:index' %}">top</a>{% include /includes/footer %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="/assets/js/app.js"></script>
  </body>
</html>

templates/works/detail.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!--Global site tag (gtag.js) - Google Analytics-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=XX-XXXXXXXX-X"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'XX-XXXXXXXX-X');
    </script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <!-- META-->
    <title>Site Title</title>
    <meta name="description" content="ページ説明">
    <meta name="keywords" content="ページキーワード,pagekeyword">
    <meta name="twitter:site" content="http://www.sitetitle.com">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:description" content="ページ説明">
    <meta name="twitter:image:src" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:title" content="Site Title">
    <meta property="og:site_name" content="Site Title">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="ja_JP">
    <meta property="og:image" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:description" content="ページ説明">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="152x152" href="/assets/favicons/favicon-152x152.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
    <link rel="mask-icon" href="/assets/favicons/safari-pinned-tab.svg" color="#000000">
    <link rel="shortcut icon" href="/assets/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="msapplication-config" content="/assets/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/app.css' %}">
  </head>
  <body>
    <div class="wrapper">{% include /includes/header %}
      <h1>{{ work.title }}</h1>{{ work.content| safe }}{% include /includes/footer %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="/assets/js/app.js"></script>
  </body>
</html>

templates/works/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!--Global site tag (gtag.js) - Google Analytics-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=XX-XXXXXXXX-X"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'XX-XXXXXXXX-X');
    </script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <!-- META-->
    <title>Site Title</title>
    <meta name="description" content="ページ説明">
    <meta name="keywords" content="ページキーワード,pagekeyword">
    <meta name="twitter:site" content="http://www.sitetitle.com">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:description" content="ページ説明">
    <meta name="twitter:image:src" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:title" content="Site Title">
    <meta property="og:site_name" content="Site Title">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="ja_JP">
    <meta property="og:image" content="http://www.sitetitle.com/assets/img/og_image.png">
    <meta property="og:description" content="ページ説明">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="152x152" href="/assets/favicons/favicon-152x152.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
    <link rel="mask-icon" href="/assets/favicons/safari-pinned-tab.svg" color="#000000">
    <link rel="shortcut icon" href="/assets/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="msapplication-config" content="/assets/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/app.css' %}">
  </head>
  <body>
    <div class="wrapper">{% include /includes/header %}{% if latest_post_list %}
      <ul>{% for post in latest_post_list %}
        <li><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></li>    {% endfor %}
      </ul>{% else %}
      <p>No posts are available.</p>{% endif %}
      {% if latest_work_list %}
      <ul>{% for work in latest_work_list %}
        <li><a href="{% url 'works:detail' work.id %}">{{ work.title }}</a></li>    {% endfor %}
      </ul>{% else %}
      <p>No posts are available.</p>{% endif %}{% include /includes/footer %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="/assets/js/app.js"></script>
  </body>
</html>